### ISSUE TITLE
Meteor restarts due to temporary files

### ISSUE THREAD

**Issue by pongo** [idok/coffee-lint-plugin#2]
Windows 7, WebStorm 10.
1. Create meteor project. Enable coffeelint plugin. Add coffeescript package. Run meteor.
2. Edit any coffeescript file (autosave disabled).
3. coffee-lint-plugin creates the file "filename_scsslint_tmp9013504531595693637.coffee"
4. Meteor detects this file and restarts.

Meteor should be restarted only after the files are saved. Could you create temporary files in the system temporary folder? Or rename their extension to .tmp?

**Comment by dettier** [comment]
+1, you should not put temporary files in project folders, as different file watching tasks might go crazy
