### ISSUE TITLE
Argument for @NotNull parameter 'path' of com/coffeelint/cli/CoffeeLintRunner.buildSettings must not be null

### ISSUE THREAD

**Issue by rodolfoprr** [idok/coffee-lint-plugin#3]
The following error appears when the plugin is executed:

10:31:22 CoffeeLint plugin: Error running CoffeeLint inspection: Argument for @NotNull parameter 'path' of com/coffeelint/cli/CoffeeLintRunner.buildSettings must not be null
10:31:22 IllegalArgumentException: Error running CoffeeLint inspection: Argument for @NotNull parameter 'path' of com/coffeelint/cli/CoffeeLintRunner.buildSettings must not be null

My config:

Node: C:\Program Files\nodejs\node.exe
Path to coffeelint bin: C:\Users\rodolfo\AppData\Roaming\npm\coffeelint.cmd

Windows 8.1
WebStorm 10.0.3
Coffeelint 1.9.7

**Comment by tomyam1** [comment]
Also got this issue.
It only happens when inspection is triggered after I change a file.
When I run inspect code myself, the plugin works.
